MBTN_LEFT      cycle pause            # Play / Pause with left mouse click
SPACE           cycle pause           # Play / Pause
s               stop
q               quit

r               seek 0 absolute       # Restart video

Right           seek 10
Left            seek -10
Up              add volume 5
Down          	add volume -5

Shift+Right     seek 3
Shift+Left      seek -3

Ctrl+Right      seek 60
Ctrl+Left       seek -60

f               cycle fullscreen

]               add speed 0.1
[               add speed -0.1


c               cycle audio
v               cycle sub
b               cycle sub-backward
j               cycle sub-visibility
