input-ipc-server=/tmp/niri_caelestia_mpv.sock
osc=no    
osd-level=1
border=no
#window-dragging=yes                   
keepaspect=yes                   
#keep-open=yes                  
force-window=yes              
cursor-autohide=1000            
autofit=70%x70%                 
hwdec=auto-safe
